version: '3.9'


services:

  airbag:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017
      - MONGO_DB_NAME=airbag
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    restart: on-failure
    container_name: mongo-db
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017